server:
  port: 8081
dog:
  name: 小狗-dev
  age: 2
  species: DOG
  sex: 公
people:
  name: servi-dev
  pets:
    - {name: 狗1, age: 1}
    - {name: 狗2, age: 2}
spring:
  datasource:
    username: root
    password: 123456a
    url: jdbc:mysql://127.0.0.1:3306/mysql?serverTimezone=Asia/Shanghai
