server:
  port: 8080
#指定默认加载的文件[application-dev.yml]
spring:
  profiles:
    active: dev
#设置支持访问 'http://localhost:8080/actuator/beans'
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'