server:
  port: 8080
dog:
  name: 小狗
  age: 2
  species: DOG
  sex: 公
people:
  name: servi
  pets:
    - {name: 狗1, age: 1}
    - {name: 狗2, age: 2}
#设置支持访问 'http://localhost:8080/actuator/beans'
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'