# oracle 数据源配置
spring:
  jpa:
    database: oracle
    show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.10.18.70:1521:orcl
    username: NC_728
    password: 1
  main:
    allow-bean-definition-overriding: true



