# oracle 数据源配置
spring:
  jpa:
    database: oracle
    show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@20.10.130.205:1521:ora12c
    username: ssc_1209
    password: 1
  main:
    allow-bean-definition-overriding: true



