# oracle 数据源配置
spring:
  jpa:
    database: oracle
    show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.20.4.122:1521:orcl
    username: ncc2012h
    password: 1
  main:
    allow-bean-definition-overriding: true



