spring:
  datasource:
    username: root
    password: 123456a
    url: jdbc:mysql://127.0.0.1:3306/servi-db?serverTimezone=Asia/Shanghai
    #    url: jdbc:mysql://172.16.86.6:3306/test?serverTimezone=Asia/Shanghai
    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5
      filters: conn,config,stat,slf4j
      filter:
        config:
          enabled: true
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true