package com.servi.study.ora._02_renametable;

/**
 * @author servi
 * @date 2020/8/22
 */
public class TablesDefine {
    public static String sscneedtable = "md_enumvalue;" +
            "md_busiactivity;" +
            "md_busiop;" +
            "md_class;" +
            "md_component;" +
            "md_opinterface;" +
            "md_property;" +
            "md_refbusiop;" +
            "md_refoperation;" +
            "md_viewcolumn;" +
            "md_accessorpara;" +
            "md_attr_table;" +
            "md_bizitfmap;" +
            "md_db_relation;" +
            "md_indexcolumn;" +
            "md_module;" +
            "md_operation;" +
            "md_parameter;" +
            "md_view;" +
            "md_association;" +
            "md_attr_busilog;" +
            "md_attr_power;" +
            "md_bean_power;" +
            "md_column;" +
            "md_comp_busimodule;" +
            "md_dev_busi_module;" +
            "md_index;" +
            "md_ormap;" +
            "md_table;" +
            "md_tree_powertype;" +
            "sm_adm_rolegrporg;" +
            "sm_adm_usrgrporg;" +
            "sm_admin_app;" +
            "sm_admin_org;" +
            "sm_admin_resource;" +
            "sm_admin_rolegroup;" +
            "sm_admin_usergroup;" +
            "sm_app_group;" +
            "sm_appbutnregister;" +
            "sm_appmenuitem;" +
            "sm_appmenureg;" +
            "sm_apppage;" +
            "sm_appparam;" +
            "sm_appregister;" +
            "sm_auto_unloading;" +
            "sm_appbusiactivereg;" +
            "sm_bdchange_reg;" +
            "sm_busiactive_permncc;" +
            "sm_busiflow_nodes;" +
            "sm_busiworkflow;" +
            "sm_busiworkflow_cell;" +
            "sm_createcorp;" +
            "sm_ctpermdetail;" +
            "sm_dpprofile_reg;" +
            "sm_flowchart_icon;" +
            "sm_gm_app;" +
            "sm_log_attribute;" +
            "sm_log_busilogrule;" +
            "sm_log_operatelogrule;" +
            "sm_metadata_rule;" +
            "sm_msg_msgtype;" +
            "sm_msg_stypebase;" +
            "sm_msg_stypeprop;" +
            "sm_msgattac_stag;" +
            "sm_ncckeyfunc;" +
            "sm_op_busiop;" +
            "sm_pageregister;" +
            "sm_paramregister;" +
            "sm_patch_version;" +
            "sm_perm_data;" +
            "sm_perm_func;" +
            "sm_permission_data;" +
            "sm_permission_res;" +
            "sm_permission_rule;" +
            "sm_product_version;" +
            "sm_pub_filesystem;" +
            "sm_res_operation;" +
            "sm_resp_app;" +
            "sm_responsibility;" +
            "sm_role;" +
            "sm_role_exclude;" +
            "sm_role_group;" +
            "sm_rule;" +
            "sm_rule_ref;" +
            "sm_rule_type;" +
            "sm_specialpermission;" +
            "sm_subject_org;" +
            "sm_themecolor;" +
            "sm_user;" +
            "sm_user_group;" +
            "sm_user_role;" +
            "sm_user_share;" +
            "sm_usergroup;" +
            "sm_workbench;" +
            "pub_actionconstrict;" +
            "pub_alertquery;" +
            "pub_alertquery_dir;" +
            "pub_alertregistry;" +
            "pub_alertregistry_org;" +
            "pub_alerttype;" +
            "pub_alerttype_b;" +
            "pub_alerttypeconfig;" +
            "pub_alertruntime;" +
            "pub_alertsendconfig;" +
            "pub_app_systemplate;" +
            "pub_area;" +
            "pub_attr_plugin;" +
            "pub_bcr_candiattr;" +
            "pub_bcr_entity;" +
            "pub_bcr_nbcr;" +
            "pub_bcr_orgrela;" +
            "pub_bcr_precode;" +
            "pub_bcr_reflect;" +
            "pub_bcr_elem;" +
            "pub_bcr_rulebase;" +
            "pub_bcr_sngenerator;" +
            "pub_billaction;" +
            "pub_billactionconfig;" +
            "pub_billactiongroup;" +
            "pub_billbackmsg;" +
            "pub_billbusiness;" +
            "pub_billflow_partner;" +
            "pub_billitfdef;" +
            "pub_billsource;" +
            "pub_billtemplet;" +
            "pub_billtemplet_b;" +
            "pub_billtemplet_t;" +
            "pub_bsexpoint;" +
            "pub_bsplugins;" +
            "pub_busiclass;" +
            "pub_eventlistener;" +
            "pub_eventtype;" +
            "pub_form_property;" +
            "pub_formdata;" +
            "pub_funccodetocode;" +
            "pub_function;" +
            "pub_generalrule;" +
            "pub_guideline;" +
            "pub_guideline_f;" +
            "pub_importregister;" +
            "pub_itfextend;" +
            "pub_messagedrive;" +
            "pub_msgres_rcv;" +
            "pub_msgres_rcvconf;" +
            "pub_msgres_reg;" +
            "pub_msgres_sfdfrcv;" +
            "pub_msgres_tmpconf;" +
            "pub_msgtemp;" +
            "pub_msgtemp_type;" +
            "pub_msgtemp_var;" +
            "pub_multilang;" +
            "pub_ncc_queryscheme;" +
            "pub_oid;" +
            "pub_page_templet;" +
            "pub_pluginitem;" +
            "pub_print_cell;" +
            "pub_print_dataitem;" +
            "pub_print_datasource;" +
            "pub_print_line;" +
            "pub_print_region;" +
            "pub_print_template;" +
            "pub_print_variable;" +
            "pub_printlimit;" +
            "pub_printpara;" +
            "pub_psn_matrix;" +
            "pub_psn_reg;" +
            "pub_psn_resource;" +
            "pub_publishapp;" +
            "pub_query_condition;" +
            "pub_query_property;" +
            "pub_query_sysfunc;" +
            "pub_query_templet;" +
            "pub_queryscheme;" +
            "pub_refenum;" +
            "pub_report_group;" +
            "pub_report_model;" +
            "pub_report_templet;" +
            "pub_riafbaction;" +
            "pub_riawftxsetup;" +
            "pub_sign;" +
            "pub_sysinit;" +
            "pub_sysinit_power;" +
            "pub_sysinittemp;" +
            "pub_systemp_audit;" +
            "pub_systemplate;" +
            "pub_systemplate_base;" +
            "pub_template_assignment;" +
            "pub_timeconfig;" +
            "pub_ufgraph;" +
            "pub_vochange;" +
            "pub_vochange_b;" +
            "pub_vochange_s;" +
            "pub_vosplititem;" +
            "pub_wf_alertctrl;" +
            "pub_wf_def;" +
            "pub_wf_def_templte;" +
            "pub_wf_parameter;" +
            "pub_wf_participant;" +
            "pub_wf_participantex;" +
            "pub_wf_termsetting;" +
            "pub_wfdef_ref;" +
            "pub_wfgadget_b;" +
            "pub_wfgroup;" +
            "pub_wfgroup_b;" +
            "pub_workflowagent;" +
            "pub_workflowgadget;" +
            "pub_workitemconfig;" +
            "bd_cachetabversion;" +
            "dap_dapsystem;" +
            "bd_refinfo;" +
            "gw_tenantinfo;" +
            "bd_billtype2;" +
            "bd_billtype;" +
            "BD_FWDBILLTYPE;" +
            "BD_RELATEDAPP;" +
            "om_post;" +
            "ORG_ORGS_V;" +
            "ORG_FINANCEORG;" +
            "ORG_FINANCEORG_V;" +
            "ORG_SETOFBOOK;" +
            "bd_currtype;" +
            "ORG_CORP;" +
            "ORG_CORP_V;" +
            "bd_workcalendar;" +
            "bd_workcalendardate;" +
            "bd_workcalendyear;" +
            "ORG_GROUP;" +
            "ORG_ORGS;" +
            "ORG_ORGS_V;" +
            "ORG_ORGTYPE;" +
            "ORG_DEPT;" +
            "ORG_DEPT_V;" +
            "BD_SUPPLIER;" +
            "bd_cust_supplier;" +
            "bd_bankaccsub;" +
            "BD_CUSTOMER;" +
            "BD_MATERIAL;" +
            "BD_MATERIAL_V;" +
            "BD_PSNDOC;" +
            "bd_bankdoc;" +
            "bd_banktype;" +
            "bd_measdoc;" +
            "sm_user_ex;" +
            "org_sscbusiunitclientage;" +
            "bd_userdefruleref;" +
            "bd_userdefrule;" +
            "bd_sharebilltype;" +
            "bd_scanconvertor;" +
            "bd_scanbilltypeinfo;" +
            "bd_imagescantype;" +
            "bd_cr_resource;" +
            "bd_inoutbusiclass;" +
            "bd_psnjob;" +
            "bd_suporg;" +
            "bd_taxcode;" +
            "bd_taxrate;" +
            "org_orgmanager;" +
            "sm_busilog_default;" +
            "sm_log_operatelog;" +
            "sm_log_unloading;" +
            "sm_msg_approve;" +
            "sm_msg_attachment;" +
            "sm_msg_notice;" +
            "sm_msg_prealert;" +
            "sm_msg_todo;" +
            "sm_msg_user;" +
            "pub_alertmessage;" +
            "pub_async;" +
            "pub_async_result;" +
            "pub_bcr_return;" +
            "pub_bcr_sn;" +
            "pub_wf_actinstance;" +
            "pub_wf_actinstancesrc;" +
            "pub_wf_def_adjust;" +
            "pub_wf_instance;" +
            "pub_wf_instance_b;" +
            "pub_wf_instance_h;" +
            "pub_wf_messagemeta;" +
            "pub_wf_rejectreason;" +
            "pub_wf_task;" +
            "pub_wf_taskreceiver;" +
            "pub_wf_txmark;" +
            "pub_wfexptlog;" +
            "pub_workflownote;" +
            "pub_workflownote_att;" +
            "pub_workingtasklog;" +
            "pub_workitemappoint;" +
            "pub_printinfo;" +
            "pub_printlog;" +
            "pub_printnumber;" +
            "pub_nccfs_file;";

    public static String ssctable = "PublicFieldDataTypeEnum;cp_appsnode;CP_APPSCATEGORY" +
            "CP_APPSNODE" +
            "CP_DATACOPY" +
            "CP_DATACOPYCONFIG" +
            "CP_DEVICE" +
            "CP_DOC" +
            "CP_DOC_ATTR" +
            "CP_DOC_EFFECT" +
            "CP_DOC_LIST" +
            "CP_DOC_OBJREL" +
            "CP_DOC_SYSATTR" +
            "CP_DOC_SYSATTRTYPE" +
            "CP_DOC_TYPE" +
            "CP_DSCONFIG" +
            "CP_EVENTLISTENER" +
            "CP_EVENTTYPE" +
            "CP_FAQ" +
            "CP_FILELOCK" +
            "CP_FREENODE" +
            "CP_GZ_CONDITION" +
            "CP_GZ_TEMPLATE" +
            "CP_LDAPIMPORTCFG" +
            "CP_MENUCATEGORY" +
            "CP_MENUITEM" +
            "CP_MODULE" +
            "CP_ORGACCREDIT" +
            "CP_ORGS" +
            "CP_PRINT_CONDITION" +
            "CP_PRINT_TEMPLATE" +
            "CP_PSNDOC" +
            "CP_PSNJOB" +
            "CP_QUERYSCHEME" +
            "CP_QUERY_CONDITION" +
            "CP_QUERY_TEMPLATE" +
            "CP_RELAPPSNODE" +
            "CP_RES" +
            "CP_RESACCREDIT" +
            "CP_RESOURCE" +
            "CP_RESPONSIBILITY" +
            "CP_RESP_FUNC" +
            "CP_RESP_RES" +
            "CP_ROLE" +
            "CP_ROLEFUNNODE" +
            "CP_ROLEGROUP" +
            "CP_ROLEORG" +
            "CP_ROLERES" +
            "CP_ROLERESP" +
            "CP_RULESCHEME" +
            "CP_SCANCFG" +
            "CP_SUBFUNC" +
            "CP_SYSINIT" +
            "CP_SYSINITTEMP" +
            "CP_TEMPLATEDEPT" +
            "CP_TEMPLATEORG" +
            "CP_TEMPLATEROLE" +
            "CP_TEMPLATEUSER" +
            "CP_USER" +
            "CP_USERGROUP" +
            "CP_USERGROUPROLE" +
            "CP_USERGROUPUSER" +
            "CP_USERROLE" +
            "cp_appsnode;" +
            "cp_doc;" +
            "cp_doc_attr;" +
            "cp_doc_sysattr;" +
            "cp_doc_sysattrtype;" +
            "cp_doc_type;" +
            "cp_menuitem;" +
            "cp_orgs;" +
            "sscrp_fieldmap_b;" +
            "sscrp_publicfieldvalue;" +
            "sscivm_invoice;" +
            "invoicetype;" +
            "enum;" +
            "InvoiceCJFS;" +
            "RzztEnum;" +
            "yhzcbs;" +
            "ssc_busi_act_op;" +
            "ssc_billitemmap;" +
            "ssc_exclusion;" +
            "sscbd_point_item;" +
            "comparemode;" +
            "ssctp_workinggroup;" +
            "maptype;" +
            "ssctp_voucheropen;" +
            "dispatchstatus;" +
            "ssctp_intellidispatchrule;" +
            "sscpfm_bgimage;" +
            "sscpfm_datatransform_conf;" +
            "sscpfm_kpi_template;" +
            "sscpfm_orgarea;" +
            "sscpfm_unit;" +
            "sscsfm_unsatisfied_reason;" +
            "flownode;" +
            "takenstate;" +
            "ssckm_knowledge;" +
            "sscqm_check_bill;" +
            "sscqm_check_bill_problem;" +
            "sscrp_bill;" +
            "sscrp_detail;" +
            "sscrp_billtransmit_log;" +
            "sscrp_usermenu;" +
            "InvoiceFreezed;" +
            "sscivm_inv_ina_relation;" +
            "sscivm_invoice_relation;" +
            "sscivm_invoice_train;" +
            "imag_task;" +
            "imag_basefactory;" +
            "bd_ImageScanSetup;" +
            "ssc_ssctasklog;" +
            "ssc_jumpconfiguration;" +
            "sscbd_apply_scope;" +
            "sscbd_problem_class;" +
            "sscbd_problem_matter;" +
            "sscbd_point_rule;" +
            "ssc_dailyreport;" +
            "ssc_BusiInfo;" +
            "ssc_busigroup;" +
            "ssctp_printrule_body;" +
            "ssctp_problem_result;" +
            "upgraderule;" +
            "ssctp_allotrule;" +
            "enablestate;" +
            "sscsfm_evaluation_rule_detail;" +
            "sscsfm_evaluated_detail;" +
            "exptype;" +
            "kmpoststatus;" +
            "sscqm_ag_template;" +
            "sscqm_check_task_condition_sub;" +
            "sscrp_detail_done;" +
            "sscrp_busiclass;" +
            "InvoiceMatchStatus;" +
            "InvoiceStatus;" +
            "fpxz;" +
            "sscivm_invoice_quota;" +
            "sscivm_invoice_voucher_bill;" +
            "image_rescan;" +
            "ImageStateEnum;" +
            "ImagFactoryEnum;" +
            "TaxFactoryEnum;" +
            "ssc_taskstate;" +
            "ssc_busiactivity;" +
            "ssc_ssctask;" +
            "ssc_BillLandMarkStateVO;" +
            "repmethods;" +
            "ssctp_unit;" +
            "sscbd_point_class;" +
            "ssc_allotrule;" +
            "SSCLadeTypeEnum;" +
            "ssctp_clientage;" +
            "sscpfm_kpi_view;" +
            "sscpfm_org_billtype_num;" +
            "sscsfm_evaluated;" +
            "SSCTP_TASKEXTENDINFO;" +
            "ssctp_approverule;" +
            "lslbs;" +
            "sscivm_invoice_air;" +
            "bd_scanbilltypeinfo;" +
            "imag_verify_record;" +
            "ssc_billapprovestatus;" +
            "ssc_wfbusioperator;" +
            "org_ssctype;" +
            "org_sscbusiunitclientage;" +
            "ssctp_laderule_b;" +
            "ssctp_detailopen;" +
            "ssctp_imagshow;" +
            "ssctp_points_result;" +
            "sscpfm_datetable;" +
            "sscpfm_flowpath;" +
            "sscpfm_theme;" +
            "sscpfm_user_num;" +
            "sscsfm_evaluation_dimension;" +
            "resultsflag;" +
            "sscqm_check_bill_point;" +
            "sscqm_check_task;" +
            "sscqm_check_task_condition;" +
            "sscqm_check_task_content;" +
            "sscivm_ivappdetail;" +
            "sscivm_invoice_roadtoll;" +
            "sscivm_invoice_task_log;" +
            "ssc_activetask;" +
            "ssc_monthreport;" +
            "ssc_wflandmarkstate;" +
            "ssc_allotrule_b;" +
            "org_sscorg_v;" +
            "org_sscbusinessunittype;" +
            "ssctp_laderule;" +
            "showtype;" +
            "ssctp_eventlistener;" +
            "ssctp_idispatchusers;" +
            "ssctp_intellidispatchlog;" +
            "sscusertype;" +
            "sscpfm_datatransform_log;" +
            "sscpfm_now_num;" +
            "sscpfm_post;" +
            "ssctp_task;" +
            "expuntreated;" +
            "ssckm_authority;" +
            "ssckm_relation;" +
            "sscqm_check_report_problem;" +
            "sscrp_bill_done;" +
            "sscivm_billfield;" +
            "sscivm_invoicedetail;" +
            "IsHzfp;" +
            "sscivm_ivapplication;" +
            "sscivm_invoice_airdetail;" +
            "sscivm_invoice_taxi;" +
            "sscivm_ivapplog;" +
            "imag_billmapping;" +
            "exigencestate;" +
            "ssc_posttask;" +
            "seriouslevel;" +
            "org_sscorg;" +
            "ssctp_ots;" +
            "ssctp_taskmap;" +
            "FieldTypeEnum;" +
            "ssctp_approve_log;" +
            "sscpfm_billtype;" +
            "sscpfm_other_charts_login;" +
            "sscpfm_timetable;" +
            "sscpfm_user;" +
            "sscsfm_unevaluate;" +
            "nodesrc;" +
            "ssctp_flowpath;" +
            "ssctp_approverule_b;" +
            "ssckm_classify;" +
            "sscqm_check_report;" +
            "sscrp_fieldmap;" +
            "sscrp_busiclass_b;" +
            "accountstatus;" +
            "sscivm_invoice_bus;" +
            "sscivm_invoice_status_task;" +
            "imag_lookupClass;" +
            "OCRFactoryEnum;" +
            "imag_ocr_record;" +
            "ssc_busioperation;" +
            "jumpposition;" +
            "sscbd_point;" +
            "Isenable;" +
            "ssc_billorg;" +
            "org_ssclientage;" +
            "SSCManageLevelEnum;" +
            "ssctp_printrule_head;" +
            "ssctp_workflowuser;" +
            "ssctp_billtaskinfo;" +
            "ssctp_dutystatelog;" +
            "ssctp_priority;" +
            "ssctp_allotrule_b;" +
            "sscpfm_task;" +
            "sscsfm_evaluation_rule;" +
            "evaluation_result_enum;" +
            "ssctp_node;" +
            "sscqm_ag_article;" +
            "sscrp_publicfield;" +
            "sscivm_billinfo;" +
            "sscivm_billtype;" +
            "classtype;" +
            "kpfs;" +
            "imag_receiver;" +
            "image_state;" +
            "ssc_persontask;" +
            "operator;" +
            "ssctp_tasktype;" +
            "ssctp_accessoryshow;" +
            "ssctp_comparison_result;" +
            "ssctp_intellidispatchrule_b;" +
            "DispatchTypeEnum;" +
            "ssctp_ranking;" +
            "type;" +
            "ssctp_workinggroup_user;" +
            "sscpfm_center_config;" +
            "sscpfm_kpi_group;" +
            "sscpfm_postallot;" +
            "sscpfm_register;" +
            "ssctp_currenttask;" +
            "actiontype;" +
            "Iscontainslower;" +
            "ssctp_approvemonitor;" +
            "ssckm_menutip;" +
            "RectificationEnum;" + "SSCTP_WORKINGGROUP_USer;";
}
